################################### Default Configuration ############################
baseurl = "//ime.unicamp.br/~mfq"
title = "MathFoundQ | Mathematical Foundations of Quantum Theory Group"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here

# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "People"
url = "people"
weight = 2

[[menu.main]]
name = "Research"
url = "research"
weight = 3

[[menu.main]]
name = "Publications"
url = "publications"
weight = 4

[[menu.main]]
name = "Nonlocal Talks"
url = "talks"
weight = 5

[[menu.main]]
name = "About Us"
url = "about"
weight = 6

[[menu.footer]]
name = "People"
url = "people"
weight = 2

# footer menu
[[menu.footer]]
name = "Research"
url = "research"
weight = 2

[[menu.footer]]
name = "Publications"
url = "publications"
weight = 4

[[menu.footer]]
name = "Talks"
url = "talks"
weight = 5

[[menu.footer]]
name = "About"
url = "about"
weight = 6

########################### Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "100px"
# Meta data
description = "Research group at University of Campinas. We study contextuality, generalized probabilistic theories, nonlocality, quantum steering and more."
author = "MFQ"
# currency
currency = "$"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Developed By MFQ | Powered By [Hugo](https://gohugo.io/) | Based on [Vex](https://github.com/themefisher/vex-hugo) By [Themefisher](https://themefisher.com/)"
